# Generated by Django 5.2.6 on 2025-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sustainability_interests',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of sustainability interests'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
