# Generated by Django 5.2.8 on 2025-11-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userhistory_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eco_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='eco_certificates/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='accounts.product')),
            ],
        ),
    ]
